= ASP.NET with NoSQL Workshop

The workshop will show developers how to build a full-stack CRUD application with Couchbase server. Angular will be used for the frontend. Application code will be written using .NET. Couchbase will be used as the backend database. You’ll learn how to do data modeling for a NoSQL-based application, learn Couchbase SDK design patterns, and learn about different tools to make you an effective user of Couchbase.

== Attendees will learn:

. Different options to install Couchbase Server
. Basic configuration of Couchbase Server
. Data modeling for NoSQL applications
. Basic N1QL syntax to manipulate data
. How to use the Couchbase SDK to perform CRUD operations
. Couchbase SDK design patterns and anti-patterns
. Effective use of developer tools such as Query Workbench, Couchbase CLI and REST API
. How to create a simple Couchbase cluster using Docker or cloud platforms such as Amazon and Azure

== Workshops

* Workshop A: Installing and setting up Couchbase
* Workshop B: Creating a "Hello, World" console application with .NET/C#
* Workshop C: Creating a RESTful ASP.NET WebAPI service
* Workshop D: Creating an Angular web application that consumes a web service

== Target Audience

Broad range of developers interested in using Couchbase Server, ASP.NET, .NET Core, NoSQL, and Angular.

== Requirements

Please have the appropriate software setup in advance so that we can maximize the time we have available for the workshop. I will be at the venue at least an hour early if you need any assistance getting set up.
 
You will need:
 
* A computer running Windows, Mac OS X, or Ubuntu 12/14 with at least 8gb of RAM.
* You will need sufficient privileges to install software on the computer.
* The source code and slides (available on Github and also available via USB thumb drive the day of the workshop)
* Slides will be available in Powerpoint and PDF format
 
For .NET development you will need:

* Visual Studio 2015 or later for .NET Framework
* Visual Studio 2017 (or Visual Studio Code) for .NET Core
 
For Angular development, you will need:

* angular-cli
* Node / npm

== Optional

If you wish to use Azure or Amazon for this workshop, you will need an account before you arrive, and some experience with using Azure/AWS.

* Azure trial sign-up with free $200 credit: https://azure.microsoft.com/en-us/free/
* Amazon AWS sign-up https://aws.amazon.com/
* Couchbase Server 4.5 Enterprise Edition is available as a free trial in the Azure and AWS Marketplaces

If you wish to use Docker, Instructions will be provided for running Couchbase Server on docker.
